[pyprland]
plugins = [
  "scratchpads"
]

[scratchpads.filemanager]
animation = ""
command = "nemo"
class = "nemo"
lazy = false
size = "60% 60%"
margin = 0

[scratchpads.musicplayer]
animation = ""
command = "spotify"
class = "Spotify"
lazy = true
size = "70% 70%"
margin = 0

[scratchpads.term]
command = "foot -a foot-float"
animation = "fromBottom"
margin = 50
unfocus = "hide"

[scratchpads.volume]
animation = "fromRight"
command = "pavucontrol"
class = "org.pulseaudio.pavucontrol"
size = "40% 90%"
unfocus = "hide"
lazy = true