[pyprland]
plugins = [
  "scratchpads"
]

[scratchpads.filemanager]
animation = ""
command = "nemo"
class = "nemo"
lazy = false
size = "60% 60%"
margin = 0

[scratchpads.musicplayer]
animation = ""
command = "spotify"
class = "Spotify"
lazy = true
size = "70% 70%"
margin = 0

[scratchpads.term]
animation = "fromTop"
command = "foot --app-id foot-dropterm"
class = "foot-dropterm"
size = "70% 60%"
margin = 50

[scratchpads.volume]
animation = "fromRight"
command = "pavucontrol"
class = "org.pulseaudio.pavucontrol"
size = "40% 90%"
unfocus = "hide"
lazy = true