[pyprland]
plugins = ["scratchpads", "system_notifier"]

[scratchpads.filemanager]
animation = ""
command = "nemo"
class = "nemo"
lazy = false
size = "60% 60%"
margin = 0

[scratchpads.musicplayer]
animation = ""
command = "spotify"
class = "Spotify"
lazy = true
size = "70% 70%"
margin = 0

[scratchpads.term]
animation = "fromTop"
command = "foot --app-id foot-dropterm"
class = "foot-dropterm"
size = "70% 60%"
margin = 50

[scratchpads.volume]
animation = "fromRight"
command = "pavucontrol"
class = "org.pulseaudio.pavucontrol"
lazy = "true"
size = "40% 90%"
max_size = "1080px 100%"
unfocus = "hide"
preserve_aspect = true

[scratchpads.telegram]
animation = ""
command = "telegram-desktop"
class = "TelegramDesktop"
lazy = true
size = "70% 70%"
margin = 0

[system_notifier]
command = "sudo journalctl -fx"
parser = ["journal"]
